# Group 13 : Digital Marketing Essentials for YouTube's Music Category
Final Report

# Citations
* Dataset: https://www.kaggle.com/datasnaek/youtube-new
* YouTube API document: https://developers.google.com/youtube/v3
* Youtube statistics: https://www.globalmediainsight.com/blog/youtube-users-statistics/

## Author(s)

- Author1 = {"Name": "Sohaira Sarood", "Affiliation": "UBC Student", "Email": "ssarood@student.ubc.ca", "Student ID": "78962081"}
- Author2 = {"Name": "Frankie Softley", "Affiliation": "UBC Student", "Email": "fsoftley@student.ubc.ca", "Student ID": "55953558"}
- Author3 = {"Name": "Kook Han", "Affiliation": "UBC Student", "Email": "kxh72410@student.ubc.ca", "Student ID": "96767348"}
- Author4 = {"Name": "Mokka Lin", "Affiliation": "UBC Student", "Email": "linzy97@student.ubc.ca", "Student ID": "32782013"}
- Author5 = {"Name": "Salil Chand", "Affiliation": "UBC Student", "Email": "salilchd@student.ubc.ca","Student ID":"26198713"}

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Group-13-:-Digital-Marketing-Essentials-for-YouTube's-Music-Category" data-toc-modified-id="Group-13-:-Digital-Marketing-Essentials-for-YouTube's-Music-Category-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Group 13 : Digital Marketing Essentials for YouTube's Music Category</a></span></li><li><span><a href="#Citations" data-toc-modified-id="Citations-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Citations</a></span><ul class="toc-item"><li><span><a href="#Author(s)" data-toc-modified-id="Author(s)-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Author(s)</a></span></li><li><span><a href="#Purpose" data-toc-modified-id="Purpose-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Purpose</a></span></li><li><span><a href="#Methods" data-toc-modified-id="Methods-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Methods</a></span></li><li><span><a href="#Results" data-toc-modified-id="Results-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>Results</a></span></li><li><span><a href="#Conclusion" data-toc-modified-id="Conclusion-2.5"><span class="toc-item-num">2.5&nbsp;&nbsp;</span>Conclusion</a></span></li></ul></li><li><span><a href="#Data-Processing-and-Analysis" data-toc-modified-id="Data-Processing-and-Analysis-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Data Processing and Analysis</a></span><ul class="toc-item"><li><span><a href="#Local-library-import" data-toc-modified-id="Local-library-import-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Local library import</a></span></li></ul></li><li><span><a href="#Parameter-definitions" data-toc-modified-id="Parameter-definitions-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Parameter definitions</a></span></li><li><span><a href="#Data-import" data-toc-modified-id="Data-import-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Data import</a></span><ul class="toc-item"><li><span><a href="#Tables-in-RDS:" data-toc-modified-id="Tables-in-RDS:-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Tables in RDS:</a></span></li><li><span><a href="#Fetching-Video-data-from-RDS" data-toc-modified-id="Fetching-Video-data-from-RDS-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>Fetching Video data from RDS</a></span></li></ul></li><li><span><a href="#Data-processing-and-analysis" data-toc-modified-id="Data-processing-and-analysis-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Data processing and analysis</a></span><ul class="toc-item"><li><span><a href="#Baseline-Model" data-toc-modified-id="Baseline-Model-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>Baseline Model</a></span></li><li><span><a href="#Linear-Regression-Model-with-sentiment-analysis" data-toc-modified-id="Linear-Regression-Model-with-sentiment-analysis-6.2"><span class="toc-item-num">6.2&nbsp;&nbsp;</span>Linear Regression Model with sentiment analysis</a></span></li><li><span><a href="#Count-Analysis-for-all-data" data-toc-modified-id="Count-Analysis-for-all-data-6.3"><span class="toc-item-num">6.3&nbsp;&nbsp;</span>Count Analysis for all data</a></span></li><li><span><a href="#Count-Analysis-for-Top-5-Categories" data-toc-modified-id="Count-Analysis-for-Top-5-Categories-6.4"><span class="toc-item-num">6.4&nbsp;&nbsp;</span>Count Analysis for Top 5 Categories</a></span></li><li><span><a href="#The-10-rules" data-toc-modified-id="The-10-rules-6.5"><span class="toc-item-num">6.5&nbsp;&nbsp;</span>The 10 rules</a></span></li><li><span><a href="#Using-notebook-template" data-toc-modified-id="Using-notebook-template-6.6"><span class="toc-item-num">6.6&nbsp;&nbsp;</span>Using notebook template</a></span></li><li><span><a href="#Adding-table-of-contents" data-toc-modified-id="Adding-table-of-contents-6.7"><span class="toc-item-num">6.7&nbsp;&nbsp;</span>Adding table of contents</a></span></li><li><span><a href="#Creating-Docker-and-Binder-for-your-notebook-repository" data-toc-modified-id="Creating-Docker-and-Binder-for-your-notebook-repository-6.8"><span class="toc-item-num">6.8&nbsp;&nbsp;</span>Creating Docker and Binder for your notebook repository</a></span></li></ul></li><li><span><a href="#References" data-toc-modified-id="References-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>References</a></span></li></ul></div>

## Purpose
Youtube is the most famous video-sharing website in the world. With increasing audience and popularity amongst the masses, it continues to be a vital tool for promotion across various industries. The platform is regarded mainly as a video-sharing site where users can watch and upload videos. However, its other features like comments, likes/dislikes, polls, and community posts also provide interaction between users. The factors which establish Youtube as a potential marketing platform are as follows:

 - Audience reach: over 2 billion monthly active users

 - Diverse customer base: age of users range from 18 years to 56+ years, with 62% male and 38% female users

 - Accessibility: There are more than a hundred local versions of YouTube in over 80 languages

It is these features that drive the objective of our analysis. We want to model and get a deeper insight into the factors that make the content impactful on youtube. The main verticals of our study are:

 - To analyze which features (likes/dislikes/comments etc.) drive “Views” across different categories such as entertainment, politics and sports

 - To investigate which keywords in the comments/descriptions attribute to “View” count

## Methods
Baseline linear regression with target field as “Views”
 - Preprocessing of variables
 - Fitting the linear regression model
 - Checking the coefficients


Linear regression Model with sentiment analysis
 - Keeping the descriptive columns
 - Drop the blank rows
 - Clean special characters and stopwords
 - Filter only results for the English language
 - Preprocessing of variables
 - Checking the coefficients

Count analysis for all data
 - Creating a Linear Regression model for the top 100 words
 - Checking the coefficients

Count analysis for top 5 categories
 - Top 5 categories
 - Top 10 negative and positive words for each category

## Results
On basis of our four analyses we see the following results:

Baseline linear regression with target field as "Views"
 - A video disliked has a higher chance of more views when compared to a liked video 
 - A video tagged to "sports" category will have higher views compared to a video tagged as "music" category
 - Comments do not necessarily increase the views. If not, they might have a negative effect

Linear regression Model with sentiment analysis
 - Negative sentiment of the description will increase the view count
 - "Comments" do increase the views count
 - A video tagged to "Comedy" category will have lower views compared to a video tagged to "Movies"

Count analysis for all data
 - Positive words leading to increased "views" are available, entertainment, play, producer, exclusive etc.
 - Negative words leading to increased "views" are episodes, link, website, production, tv etc.

Count analysis for top 5 categories
 - This analysis shows the top words for each of the categories

 
 NOTE: the causal relationship between the response and predictor variables is out of scope for this analysis

## Conclusion
 - Disabling ratings and enabling comments could lead to increased views
 - Description sentiment exhibits a negative correlation with views i.e. A negatively phrased video description will lead to less viewers
 - “Entertainment”, “play” and “exclusive” exhibit the greatest correlation with views and so where possible, should be incorporated into video descriptions

# Data Processing and Analysis

In [4]:
# Data manipulation
import pandas as pd
import numpy as np

# Options for pandas
pd.options.display.max_columns = 50
pd.options.display.max_rows = 30

# Visualizations
import plotly
import plotly.graph_objs as go
import plotly.offline as ply
plotly.offline.init_notebook_mode(connected=True)

# Autoreload extension
if 'autoreload' not in get_ipython().extension_manager.loaded:
    %load_ext autoreload
    
%autoreload 2

## Local library import
Import all the required local libraries.

You can use the sample code below to reference location of these libraries.
When packaging the notebook for submission to EarthCube, please include the libraries in a sub-directory. The local libraries should be well documented to ease reviewing.

In [5]:
# Include local library paths
import sys
# sys.path.append('path/to/local/lib') # uncomment and fill to import local libraries

# Import local libraries

# Parameter definitions
Set all relevant parameters for the notebook. By convention, parameters are uppercase, while all the other variables follow Python's guidelines.


# Data import
Retrieve all the required data for the analysis. Include brief data descriptions, and DOIs where possible.

Please import data in one of two ways:
1. Reference data that is available online and continuously managed (preferred). 
2. If the data is relatively small, please include the files along with the notebook. If you deal with large data, include a subset.

## Tables in RDS:

test.categories: contains category information  
test.channels: contains channel information  
test.tags: contains tag information  
test.videos: contains video information  
test.videos_tags: contains tag list for each video information

## Fetching Video data from RDS

In [6]:
import os
import psycopg2

from dotenv import load_dotenv
load_dotenv()

# conString = {'host':os.environ.get('DB_HOST'),
#              'dbname':os.environ.get('DB_NAME'),
#              'user':os.environ.get('DB_USER'),
#              'password':os.environ.get('DB_PASS'),
#              'port':os.environ.get('DB_PORT')}

conString = {'host': 'database-1.crsnkstbqrgk.us-west-2.rds.amazonaws.com',
 'dbname': 'postgres',
 'user': 'postgres',
 'password': 'mbanmban',
 'port': '5432'}                
                
conn = psycopg2.connect(**conString)
cur = conn.cursor()

Python-dotenv could not parse statement starting at line 1

In [42]:
conn.rollback()
query = """SELECT v.video_id, v.title, n.channel_title, 
            c.category_name, v.publish_time, v.views, v.likes, 
            v.dislikes, v.comment_count, v.thumbnail_link, v.comments_disabled, 
            v.ratings_disabled, v.video_error_or_removed, v.description
            FROM test.videos as v
            LEFT JOIN test.categories as c
            ON v.category_id = c.category_id
            LEFT JOIN test.channels as n
            ON v.channel_id = n.channel_id
            ORDER BY v.views desc;"""
cur.execute(query)
row = cur.fetchall()
#print(row[:1])

In [47]:
# DataFrames:
# videos - video table including all region

videos = pd.DataFrame(row, columns = ['video_id', 'title', 'channel_title', 
            'category_name', 'publish_time', 'views', 'likes', 
            'dislikes', 'comment_count', 'thumbnail_link', 'comments_disabled', 
            'ratings_disabled', 'video_error_or_removed', 'description'])
videos.head(3)

,video_id,title,channel_title,category_name,publish_time,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,_I_D_8Z4sJE,Nicky Jam x J. Balvin - X (EQUIS) | Video Ofic...,NickyJamTV,Music,2018-03-02 05:00:19,424538912,2818771,149275,99380,https://i.ytimg.com/vi/_I_D_8Z4sJE/default.jpg,False,False,False,Disponible en tu plataforma preferida:\nhttps:...
1,9jI-z9QN6g8,"Te Bote Remix - Casper, Nio GarcÃ­a, Darell, N...",Flow La Movie,Music,2018-04-11 22:00:00,337621571,2581961,166549,113564,https://i.ytimg.com/vi/9jI-z9QN6g8/default.jpg,False,False,False,Flow La Movie Presenta - Te BotÃ© Remix - Casp...
2,kLpH1nSLJSs,Bad Bunny - Amorfoda | Video Oficial,Bad Bunny,Music,2018-02-15 00:00:03,328860380,3823879,215530,225216,https://i.ytimg.com/vi/kLpH1nSLJSs/default.jpg,False,False,False,Bad Bunny - Amorfoda | Video Oficial\n\n-Click...

# Data processing and analysis
The core of the notebook is here. Split this section into subsections as required, and explain processing and analysis steps.

Selected best practices for organizing and formatting your notebooks are included below.

## Baseline Model

In [119]:
# Baseline Model - Linear regression

# forming df for baseline model and checking missing value in df

baseline_df = videos.drop(columns = ['channel_title', 'video_id','title','publish_time','thumbnail_link','description'])
baseline_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30318 entries, 0 to 30317
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   category_name           30318 non-null  object
 1   views                   30318 non-null  int64
 2   likes                   30318 non-null  int64
 3   dislikes                30318 non-null  int64
 4   comment_count           30318 non-null  int64
 5   comments_disabled       30318 non-null  bool
 6   ratings_disabled        30318 non-null  bool
 7   video_error_or_removed  30318 non-null  bool
dtypes: bool(3), int64(4), object(1)
memory usage: 1.2+ MB

In [92]:
# Spliting X and y

baseline_X = baseline_df.drop(columns = ['views'])
baseline_y = baseline_df['views']

In [101]:
# Preprocessing for X variables

baseline_X['comments_disabled'] = baseline_X['comments_disabled'].astype('int')
baseline_X['ratings_disabled'] = baseline_X['ratings_disabled'].astype('int')
baseline_X['video_error_or_removed'] = baseline_X['video_error_or_removed'].astype('int')
baseline_X['category_name'] = videos['category_name']
baseline_X = pd.get_dummies(baseline_X)
baseline_X

,likes,dislikes,comment_count,comments_disabled,ratings_disabled,video_error_or_removed,category_name_Autos & Vehicles,category_name_Comedy,category_name_Education,category_name_Entertainment,...,category_name_Movies,category_name_Music,category_name_News & Politics,category_name_Nonprofits & Activism,category_name_People & Blogs,category_name_Pets & Animals,category_name_Science & Technology,category_name_Shows,category_name_Sports,category_name_Travel & Events
0,2818771,149275,99380,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,2581961,166549,113564,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2,3823879,215530,225216,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,1618180,151147,67506,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
4,5444541,379862,553371,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30313,2,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
30314,9,0,0,1,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
30315,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
30316,10,2,5,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
30317,9,0,4,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0

In [120]:
# Fitting Linear Regression Model and Summary for the model

import statsmodels.api as sm

lin_reg = sm.OLS(baseline_y, baseline_X).fit()

lin_reg.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  views   R-squared:                       0.706
Model:                            OLS   Adj. R-squared:                  0.706
Method:                 Least Squares   F-statistic:                     3312.
Date:                Thu, 03 Feb 2022   Prob (F-statistic):               0.00
Time:                        22:02:39   Log-Likelihood:            -5.0100e+05
No. Observations:               30318   AIC:                         1.002e+06
Df Residuals:                   30295   BIC:                         1.002e+06
Df Model:                          22
Covariance Type:            nonrobust
=======================================================================================================
                                          coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------
likes                                  58.8951      0.267    220.415      0.000      58.371      59.419
dislikes                              129.7981      1.833     70.817      0.000     126.206     133.391
comment_count                        -201.6851      2.253    -89.500      0.000    -206.102    -197.268
comments_disabled                   -4.424e+04   1.73e+05     -0.255      0.799   -3.84e+05    2.96e+05
ratings_disabled                     9.575e+05   2.44e+05      3.929      0.000     4.8e+05    1.44e+06
video_error_or_removed              -4.972e+05   8.13e+05     -0.611      0.541   -2.09e+06     1.1e+06
category_name_Autos & Vehicles       3.279e+05   2.06e+05      1.590      0.112   -7.63e+04    7.32e+05
category_name_Comedy                -9.109e+05   7.62e+04    -11.960      0.000   -1.06e+06   -7.62e+05
category_name_Education             -1.105e+05   1.32e+05     -0.840      0.401   -3.68e+05    1.47e+05
category_name_Entertainment           3.92e+04   3.73e+04      1.052      0.293   -3.38e+04    1.12e+05
category_name_Film & Animation       1.753e+05   9.62e+04      1.822      0.068   -1.32e+04    3.64e+05
category_name_Gaming                -1.334e+05   1.17e+05     -1.137      0.255   -3.63e+05    9.65e+04
category_name_Howto & Style         -4.155e+04   8.63e+04     -0.482      0.630   -2.11e+05    1.28e+05
category_name_Movies                 1.988e+06   3.64e+06      0.547      0.585   -5.14e+06    9.11e+06
category_name_Music                 -2.938e+05    7.7e+04     -3.814      0.000   -4.45e+05   -1.43e+05
category_name_News & Politics        2.383e+05    6.3e+04      3.784      0.000    1.15e+05    3.62e+05
category_name_Nonprofits & Activism -1.212e+06   4.48e+05     -2.705      0.007   -2.09e+06   -3.34e+05
category_name_People & Blogs        -1.093e+05   6.59e+04     -1.659      0.097   -2.38e+05    1.98e+04
category_name_Pets & Animals          9.08e+04   2.01e+05      0.452      0.652   -3.03e+05    4.85e+05
category_name_Science & Technology   2.065e+04   1.21e+05      0.170      0.865   -2.17e+05    2.58e+05
category_name_Shows                  3.193e+05   3.42e+05      0.934      0.351   -3.51e+05     9.9e+05
category_name_Sports                 3.451e+05    7.4e+04      4.665      0.000       2e+05     4.9e+05
category_name_Travel & Events        2.204e+05   2.32e+05      0.951      0.342   -2.34e+05    6.75e+05
==============================================================================
Omnibus:                    72566.697   Durbin-Watson:                   1.256
Prob(Omnibus):                  0.000   Jarque-Bera (JB):       2723328437.483
Skew:                          24.052   Prob(JB):                         0.00
Kurtosis:                    1470.480   Cond. No.                     2.15e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.15e+07. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [121]:
# Coefficients

round(lin_reg.params,2)

likes                                       58.90
dislikes                                   129.80
comment_count                             -201.69
comments_disabled                       -44238.96
ratings_disabled                        957473.34
video_error_or_removed                 -497200.65
category_name_Autos & Vehicles          327881.81
category_name_Comedy                   -910897.04
category_name_Education                -110496.85
category_name_Entertainment              39200.62
category_name_Film & Animation          175278.30
category_name_Gaming                   -133396.78
category_name_Howto & Style             -41550.93
category_name_Movies                   1987862.38
category_name_Music                    -293845.01
category_name_News & Politics           238302.20
category_name_Nonprofits & Activism   -1212046.68
category_name_People & Blogs           -109276.79
category_name_Pets & Animals             90797.00
category_name_Science & Technology       20648.43
category_name_Shows                     319271.35
category_name_Sports                    345055.39
category_name_Travel & Events           220411.54
dtype: float64

## Linear Regression Model with sentiment analysis

In [152]:
# Linear Regression Model with sentiment analysis for descriptions

# preparing new DF for sentiment analysis

text_analysis_df = videos.drop(columns = ['channel_title', 'video_id','publish_time','thumbnail_link'])
text_analysis_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30318 entries, 0 to 30317
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   title                   30318 non-null  object
 1   category_name           30318 non-null  object
 2   views                   30318 non-null  int64
 3   likes                   30318 non-null  int64
 4   dislikes                30318 non-null  int64
 5   comment_count           30318 non-null  int64
 6   comments_disabled       30318 non-null  bool
 7   ratings_disabled        30318 non-null  bool
 8   video_error_or_removed  30318 non-null  bool
 9   description             29243 non-null  object
dtypes: bool(3), int64(4), object(3)
memory usage: 1.7+ MB

In [151]:
# Dropping rows which does not have descriptions

text_analysis_df = text_analysis_df.dropna(axis = 0)
text_analysis_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 29243 entries, 0 to 30317
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   title                   29243 non-null  object
 1   category_name           29243 non-null  object
 2   views                   29243 non-null  int64
 3   likes                   29243 non-null  int64
 4   dislikes                29243 non-null  int64
 5   comment_count           29243 non-null  int64
 6   comments_disabled       29243 non-null  bool
 7   ratings_disabled        29243 non-null  bool
 8   video_error_or_removed  29243 non-null  bool
 9   description             29243 non-null  object
dtypes: bool(3), int64(4), object(3)
memory usage: 1.9+ MB

In [155]:
text_analysis_df['description'] = text_analysis_df['description'].astype('str')

In [ ]:
!pip install textblob
!pip install langdetect
!pip install nltk

In [337]:
# Preprocessing for titles and descriptions (Removing special characters and stopwords)

from textblob import TextBlob
from nltk.corpus import stopwords
import re
import nltk

nltk.download('stopwords')

en_stops = stopwords.words('english')

cleaned_title = []

for x in text_analysis_df['title'].tolist():
    x = re.sub('[^0-9a-zA-Z \t]+','',x)
    x_list = x.split(' ')
    new_xl = []
    for xc in x_list:
        if xc not in en_stops and 'http' not in xc:
            new_xl.append(xc)
    new_xl = filter(lambda x: x != '', new_xl)
    new_x = ' '.join(new_xl)
    cleaned_title.append(new_x)

cleaned_title


cleaned_desc = []

for d in text_analysis_df['description'].tolist():
    d = re.sub('[^0-9a-zA-Z \t]+','', d)
    d_list = d.split(' ')
    new_dl = []
    for dc in d_list:
        if dc not in en_stops and 'http' not in dc:
            new_dl.append(dc)
    new_dl = filter(lambda nd: nd != '', new_dl)
    new_d = ' '.join(new_dl)
    cleaned_desc.append(new_d)

text_analysis_df['cleaned_title'] = cleaned_title
text_analysis_df['cleaned_desc'] = cleaned_desc

text_analysis_df

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/kookhan/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

,title,category_name,views,likes,dislikes,comment_count,comments_disabled,ratings_disabled,video_error_or_removed,description,title_sentiment,title_subjectivity,desc_sentiment,desc_subjectivity,cleaned_title,cleaned_desc
0,Nicky Jam x J. Balvin - X (EQUIS) | Video Ofic...,Music,424538912,2818771,149275,99380,False,False,False,Disponible en tu plataforma preferida:\nhttps:...,0.000000,0.000000,0.000000,0.000000,Nicky Jam x J Balvin X EQUIS Video Oficial Pro...,Disponible en tu plataforma nnNicky Jam J Balv...
1,"Te Bote Remix - Casper, Nio GarcÃ­a, Darell, N...",Music,337621571,2581961,166549,113564,False,False,False,Flow La Movie Presenta - Te BotÃ© Remix - Casp...,-0.700000,0.666667,-0.700000,0.666667,Te Bote Remix Casper Nio Garca Darell Nicky Ja...,Flow La Movie Presenta Te Bot Remix Casper Nio...
2,Bad Bunny - Amorfoda | Video Oficial,Music,328860380,3823879,215530,225216,False,False,False,Bad Bunny - Amorfoda | Video Oficial\n\n-Click...,-0.700000,0.666667,-0.700000,0.666667,Bad Bunny Amorfoda Video Oficial,Bad Bunny Amorfoda Video OficialnnClick para s...
3,Ozuna x Romeo Santos - El Farsante Remix,Music,288811992,1618180,151147,67506,False,False,False,DESCARGA Odisea Aqui: http://apple.co/2vX00sT\...,0.000000,0.000000,0.000000,0.000000,Ozuna x Romeo Santos El Farsante Remix,DESCARGA Odisea Aqui Odisea The GamenApp Store...
4,Childish Gambino - This Is America (Official V...,Music,259721696,5444541,379862,553371,False,False,False,âThis is Americaâ by Childish Gambino http...,-0.200000,0.800000,0.100000,0.600000,Childish Gambino This Is America Official Video,This America Childish Gambino Hiro MuraiProduc...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30313,Huffy Metaloid Bicycle Commercial 1997,Education,773,2,0,0,False,False,False,Anyone have one of those?,0.000000,0.000000,0.000000,0.000000,Huffy Metaloid Bicycle Commercial 1997,Anyone one
30314,"Raw: 3 South Carolina Deputies, 1 Officer Shot",News & Politics,748,9,0,0,True,False,False,Three deputies and one police officer were sho...,0.134615,0.730769,0.206618,0.435294,Raw 3 South Carolina Deputies 1 Officer Shot,Three deputies one police officer shot wounded...
30315,Artwork Forge,Sports,745,1,0,0,False,False,False,Artwork Forge II - an art installation created...,0.000000,0.000000,-0.030833,0.273333,Artwork Forge,Artwork Forge II art installation created arti...
30316,Coach Taggart Monday Presser Ahead of Arizona,Sports,704,10,2,5,False,False,False,Coach Taggart addresses the media ahead of the...,0.000000,0.000000,0.000000,0.000000,Coach Taggart Monday Presser Ahead Arizona,Coach Taggart addresses media ahead Ducks matc...
30317,"1 dead, others injured after Ky. school shooting",News & Politics,559,9,0,4,False,False,False,Kentucky Gov. Matt Bevin confirmed there was a...,-0.200000,0.400000,0.312000,0.508000,1 dead others injured Ky school shooting,Kentucky Gov Matt Bevin confirmed shooting hig...

In [348]:
# finding languages for descriptions

from langdetect import detect

title = []

title_lang = []
for text in text_analysis_df['cleaned_title'].tolist():
    try:
        title_lang.append(detect(text))
    except:
        title_lang.append('none')

        
desc_lang = []
for desc in text_analysis_df['cleaned_desc'].tolist():
    try:
        desc_lang.append(detect(desc))
    except:
        desc_lang.append('none')

text_analysis_df['title_language'] = title_lang
text_analysis_df['desc_language'] = desc_lang

text_analysis_df['desc_language'].value_counts()

en      25614
fr       1264
no       1151
af        352
none      347
de        304
ca        157
vi        151
tl        143
cy        132
es         90
id         88
it         79
pt         62
nl         55
tr         43
et         37
sl         37
sv         32
ro         27
sw         25
hr         25
so         23
pl         22
da         19
fi         15
hu         11
sk          5
lt          3
cs          3
sq          2
Name: desc_language, dtype: int64

In [356]:
# choosing descriptions written in English

text_analysis_df_en = text_analysis_df.query("desc_language == 'en'")

In [368]:
# Adding sentiment and subjectivity for each english description

desc_pol = []
desc_subj = []
for desc in text_analysis_df_en['cleaned_desc'].tolist():
    desc_pol.append(TextBlob(desc).sentiment[0])
    desc_subj.append(TextBlob(desc).sentiment[1])

text_analysis_df_en['desc_sentiment'] = desc_pol
text_analysis_df_en['desc_subjectivity'] = desc_subj

text_analysis_df_en.columns

Index(['title', 'category_name', 'views', 'likes', 'dislikes', 'comment_count',
       'comments_disabled', 'ratings_disabled', 'video_error_or_removed',
       'description', 'desc_sentiment', 'desc_subjectivity', 'cleaned_title',
       'cleaned_desc', 'title_language', 'desc_language'],
      dtype='object')

In [369]:
# Choosing variables for the linear regression model

text_analysis_final_df = text_analysis_df_en[['category_name', 'views', 'likes', 'dislikes', 'comment_count',
       'comments_disabled', 'ratings_disabled', 'video_error_or_removed',
       'desc_sentiment', 'desc_subjectivity']]

In [409]:
# Spliting X and y

NLP_X = text_analysis_final_df.drop(columns = ['views'])
NLP_y = text_analysis_final_df['views']

In [385]:
NLP_X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 25614 entries, 1 to 30317
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   category_name           25614 non-null  object
 1   likes                   25614 non-null  int64
 2   dislikes                25614 non-null  int64
 3   comment_count           25614 non-null  int64
 4   comments_disabled       25614 non-null  bool
 5   ratings_disabled        25614 non-null  bool
 6   video_error_or_removed  25614 non-null  bool
 7   desc_sentiment          25614 non-null  float64
 8   desc_subjectivity       25614 non-null  float64
dtypes: bool(3), float64(2), int64(3), object(1)
memory usage: 1.4+ MB

In [410]:
# Preprocessing for numerical X variables

from sklearn.preprocessing import StandardScaler

NLP_X['comments_disabled'] = NLP_X['comments_disabled'].astype('int')
NLP_X['ratings_disabled'] = NLP_X['ratings_disabled'].astype('int')
NLP_X['video_error_or_removed'] = NLP_X['video_error_or_removed'].astype('int')

In [411]:
# Preprocessing for categorical X variable

NLP_X['category_name'] = videos['category_name']
NLP_X = pd.get_dummies(NLP_X)
NLP_X

,likes,dislikes,comment_count,comments_disabled,ratings_disabled,video_error_or_removed,desc_sentiment,desc_subjectivity,category_name_Autos & Vehicles,category_name_Comedy,...,category_name_Movies,category_name_Music,category_name_News & Politics,category_name_Nonprofits & Activism,category_name_People & Blogs,category_name_Pets & Animals,category_name_Science & Technology,category_name_Shows,category_name_Sports,category_name_Travel & Events
1,2581961,166549,113564,0,0,0,-0.700000,0.666667,0,0,...,0,1,0,0,0,0,0,0,0,0
2,3823879,215530,225216,0,0,0,-0.700000,0.666667,0,0,...,0,1,0,0,0,0,0,0,0,0
3,1618180,151147,67506,0,0,0,0.000000,0.000000,0,0,...,0,1,0,0,0,0,0,0,0,0
4,5444541,379862,553371,0,0,0,0.100000,0.600000,0,0,...,0,1,0,0,0,0,0,0,0,0
5,4737873,117198,301756,0,0,0,0.250000,0.400000,0,0,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30312,9,5,0,1,0,0,0.144531,0.412500,0,0,...,0,0,1,0,0,0,0,0,0,0
30314,9,0,0,1,0,0,0.143750,0.421429,0,0,...,0,0,1,0,0,0,0,0,0,0
30315,1,0,0,0,0,0,-0.030833,0.273333,0,0,...,0,0,0,0,0,0,0,0,1,0
30316,10,2,5,0,0,0,0.000000,0.000000,0,0,...,0,0,0,0,0,0,0,0,1,0
30317,9,0,4,0,0,0,0.186667,0.513333,0,0,...,0,0,1,0,0,0,0,0,0,0

In [412]:
# Fitting Linear Regression Model and Summary for the model

lin_reg = sm.OLS(NLP_y, NLP_X).fit()

lin_reg.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  views   R-squared:                       0.727
Model:                            OLS   Adj. R-squared:                  0.727
Method:                 Least Squares   F-statistic:                     2840.
Date:                Sat, 05 Feb 2022   Prob (F-statistic):               0.00
Time:                        22:51:28   Log-Likelihood:            -4.2154e+05
No. Observations:               25614   AIC:                         8.431e+05
Df Residuals:                   25589   BIC:                         8.433e+05
Df Model:                          24
Covariance Type:            nonrobust
=======================================================================================================
                                          coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------
likes                                  57.6197      0.301    191.166      0.000      57.029      58.211
dislikes                              112.2199      1.944     57.722      0.000     108.409     116.031
comment_count                        -193.7563      2.378    -81.481      0.000    -198.417    -189.095
comments_disabled                    7.636e+04   1.74e+05      0.440      0.660   -2.64e+05    4.17e+05
ratings_disabled                     1.142e+06   2.74e+05      4.173      0.000    6.05e+05    1.68e+06
video_error_or_removed              -6.598e+05   8.02e+05     -0.823      0.410   -2.23e+06    9.11e+05
desc_sentiment                      -5.003e+05    1.1e+05     -4.567      0.000   -7.15e+05   -2.86e+05
desc_subjectivity                    1.504e+04   1.01e+05      0.149      0.882   -1.83e+05    2.13e+05
category_name_Autos & Vehicles       4.289e+05   2.04e+05      2.098      0.036    2.82e+04     8.3e+05
category_name_Comedy                -5.606e+05    9.1e+04     -6.157      0.000   -7.39e+05   -3.82e+05
category_name_Education              1.026e+04   1.36e+05      0.076      0.940   -2.55e+05    2.76e+05
category_name_Entertainment          1.189e+05    5.7e+04      2.086      0.037    7189.597    2.31e+05
category_name_Film & Animation       2.984e+05   1.08e+05      2.761      0.006    8.65e+04     5.1e+05
category_name_Gaming                 3.434e+04   1.22e+05      0.281      0.778   -2.05e+05    2.73e+05
category_name_Howto & Style          6.471e+04    9.6e+04      0.674      0.500   -1.23e+05    2.53e+05
category_name_Movies                 2.238e+06    3.4e+06      0.659      0.510   -4.42e+06     8.9e+06
category_name_Music                 -2.134e+05   8.48e+04     -2.517      0.012    -3.8e+05   -4.72e+04
category_name_News & Politics        3.217e+05   7.52e+04      4.276      0.000    1.74e+05    4.69e+05
category_name_Nonprofits & Activism -2.565e+05   4.68e+05     -0.548      0.584   -1.17e+06    6.62e+05
category_name_People & Blogs        -5.129e+04   8.12e+04     -0.631      0.528   -2.11e+05    1.08e+05
category_name_Pets & Animals         1.611e+05   1.99e+05      0.808      0.419    -2.3e+05    5.52e+05
category_name_Science & Technology   1.263e+05   1.27e+05      0.998      0.318   -1.22e+05    3.74e+05
category_name_Shows                  6.007e+05   4.72e+05      1.273      0.203   -3.24e+05    1.53e+06
category_name_Sports                 4.781e+05   8.36e+04      5.719      0.000    3.14e+05    6.42e+05
category_name_Travel & Events         3.74e+05   2.29e+05      1.636      0.102   -7.41e+04    8.22e+05
==============================================================================
Omnibus:                    55888.686   Durbin-Watson:                   1.335
Prob(Omnibus):                  0.000   Jarque-Bera (JB):       1091246339.207
Skew:                          19.240   Prob(JB):                         0.00
Kurtosis:                    1013.447   Cond. No.                     2.03e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.03e+07. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [413]:
# Coefficients

round(lin_reg.params,2)

likes                                       57.62
dislikes                                   112.22
comment_count                             -193.76
comments_disabled                        76359.92
ratings_disabled                       1141803.57
video_error_or_removed                 -659764.80
desc_sentiment                         -500345.74
desc_subjectivity                        15035.81
category_name_Autos & Vehicles          428913.82
category_name_Comedy                   -560568.57
category_name_Education                  10263.62
category_name_Entertainment             118915.98
category_name_Film & Animation          298374.11
category_name_Gaming                     34341.27
category_name_Howto & Style              64705.49
category_name_Movies                   2238004.24
category_name_Music                    -213358.12
category_name_News & Politics           321709.03
category_name_Nonprofits & Activism    -256525.30
category_name_People & Blogs            -51294.94
category_name_Pets & Animals            161104.83
category_name_Science & Technology      126293.69
category_name_Shows                     600655.34
category_name_Sports                    478106.98
category_name_Travel & Events           373966.82
dtype: float64

## Count Analysis for all data

In [469]:
# Choosing variables for the word count analysis

word_count_df = text_analysis_df_en[['cleaned_desc', 'views']]

# Spliting X and y

word_count_X = word_count_df['cleaned_desc']
word_count_y = word_count_df['views']


# Scaling for y as its values are too high

sds = StandardScaler()

word_count_y = pd.DataFrame(word_count_y, columns = ['views'])
word_count_y = sds.fit_transform(word_count_y)
word_count_y

array([[51.7400538 ],
       [50.39252376],
       [44.23281264],
       ...,
       [-0.18829739],
       [-0.18830369],
       [-0.188326  ]])

In [510]:
# choosing 100 words for counting

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import TruncatedSVD

cv = CountVectorizer(max_features = 100, min_df = 3, max_df = 0.8, stop_words='english')

word_count_X = cv.fit_transform(word_count_df['cleaned_desc'])
word_count_X = word_count_X.toarray()

In [511]:
# Linear Regression model for counts for 100 words

from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(word_count_X, word_count_y)

LinearRegression()

In [512]:
# Coefficients of the model

coef_df = pd.DataFrame({
    'words': cv.get_feature_names(),
    'coefficient': lr.coef_[0]
})

coef_df

/Users/kookhan/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

        words  coefficient
0         app    -0.041668
1   available     0.271262
2      awards    -0.020246
3        best    -0.015472
4         big     0.052424
..        ...          ...
95        way    -0.017707
96    website    -0.062027
97       week    -0.052784
98      world    -0.004561
99    youtube    -0.009467

[100 rows x 2 columns]

In [513]:
len(coef_df['coefficient'].unique())

100

In [514]:
# Top 10 positive words

coef_df.sort_values(by = 'coefficient', ascending=False)[:10]

            words  coefficient
1       available     0.271262
17  entertainment     0.195612
62           play     0.148186
64       producer     0.120990
20      exclusive     0.112944
59       official     0.083860
54          music     0.071410
25         follow     0.066197
4             big     0.052424
89          video     0.040202

In [515]:
# Top 10 negative words

coef_df.sort_values(by = 'coefficient', ascending=True)[:10]

         words  coefficient
19    episodes    -0.073542
44        link    -0.062964
96     website    -0.062027
65  production    -0.057869
86          tv    -0.054062
97        week    -0.052784
29      google    -0.050328
78     support    -0.049602
70       shows    -0.048396
69       share    -0.047424

## Count Analysis for Top 5 Categories

In [560]:
# Top 5 categories

categories = text_analysis_df_en['category_name'].value_counts()
top_5_categories = categories.index[:5]
top_5_categories

Index(['Entertainment', 'News & Politics', 'People & Blogs', 'Music',
       'Sports'],
      dtype='object')

In [550]:
top_10_words = pd.DataFrame({'ranking':range(1,11)}, index = range(1,11))

In [558]:
# Modeling and making dataframe for coefficients

for cat in top_5_categories:
    word_count_df = text_analysis_df_en.query("category_name == "+"'"+cat+"'")

    word_count_X = word_count_df['cleaned_desc']
    word_count_y = word_count_df['views']

    word_count_y = pd.DataFrame(word_count_y, columns = ['views'])
    word_count_y = sds.fit_transform(word_count_y)

    cv = CountVectorizer(max_features = 100, min_df = 3, max_df = 0.8, stop_words='english')

    word_count_X = cv.fit_transform(word_count_df['cleaned_desc'])
    word_count_X = word_count_X.toarray()

    lr = LinearRegression()
    lr.fit(word_count_X, word_count_y)

    coef_df = pd.DataFrame({
        'words': cv.get_feature_names(),
        'coefficient': lr.coef_[0]
    })

    coef_df.sort_values(by = 'coefficient', ascending=False)[:10].index

    top_10_words[f'{cat}_pos'] = coef_df.sort_values(by = 'coefficient', ascending=False)[:10]['words'].tolist()
    top_10_words[f'{cat}_neg'] = coef_df.sort_values(by = 'coefficient', ascending=True)[:10]['words'].tolist()

/Users/kookhan/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
/Users/kookhan/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
/Users/kookhan/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
/Users/kookhan/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
/Users/kookhan/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

In [559]:
# Top 10 positive or negative words from top 5 categories

top_10_words

,ranking,Entertainment_pos,Entertainment_neg,News & Politics_pos,News & Politics_neg,People & Blogs_pos,People & Blogs_neg,Music_pos,Music_neg,Sports_pos,Sports_neg
1,1,cbs,online,informed,programming,snapchat,chappell,performing,ntata,joy,taylor
2,2,producer,drama,coverage,fair,production,drama,entertainment,north,svp,uptotheminute
3,3,film,culture,reaching,hosted,audio,awesome,director,south,iphone,watchespn
4,4,favorite,talk,offers,ondemand,used,drag,recordings,set,commentary,edited
5,5,hum,digital,awardwinning,commentary,series,story,spotify,videos,use,fair
6,6,tumblr,television,follow,hour,merch,enjoy,available,youtube,guideline,river
7,7,vaani,app,years,movement,stars,tumblr,east,watch,espncom,property
8,8,th,taarak,use,copyright,click,watching,docomo,download,content,underwater
9,9,follow,making,game,entertainment,world,know,instagram,right,college,channel
10,10,media,things,video,website,warner,view,caller,twitter,watch,diving



## The 10 rules
These recommendations are based on [6]

1. Tell a story for an audience: interleave explanatory text with code and results to create a computational narrative.

2. Document the process, not just the results: so that others, and yourself later, will understand your reasoning and choices.

3. Use cell divisions to make steps clear: have eaach cell perform one meaningful and documented step, avoid long cells.

4. Modularize code: use and document functions for repeated operations to make the code more readable and save space.

5. Record dependencies: use pip or Conda package manager, with environment.yml (Conda) or requirements.txt (pip). Please indicate package versions explicitly. Ideally, include a listing of dependencies at the bottom of the notebook. Make sure you test your notebook in an environment created from these dependencies, so that you don't add undocumened dependencies.

6. Use version control: https://github.com/jupyter/nbdime is a diffing tool specifically designed for notebooks; you may find it useful.

7. Build a pipeline: place key variable declarations at the top. Test with different parameters, clean up, and run all cells to prepare for potential non-interactive execution.

8. Share and explain your data: if the original data are too big, inlude a sample. Make sure that the data is accessible. Include data description, and any processing done beforehand. Ideally, point to datasets that have been permanently managed and identified by DOIs.

9. Design your notebooks to be read, run, and explored:  
    9.1. Read: store it in a public code repository with a clear README file and a liberal open source license. Generate HTML/PDF versions of the final notebook.  
    9.2. Run: use Binder to run it in the cloud, and/or create a Docker image.  
    9.3. Explore: use interactive widgets (e.g., ipywidgets, or panel) 
    
10. Advocate for open research: ask your colleagues or friends to try to run your notebooks.


__Additional recommendations, beyond the 10 rules:__
1. Do not include shell commands in cells (unless the notebook will be distributed in Docker container.)
2. Keep cell output if other researchers will use the included data, or clear cell output if they will use their own data.
3. Develop your code in a clean virtual environment, to avoid dependency conflicts and streamline packaging.

To create a virtual environment, use
```
conda create -n <enviroment_name> python=3 jupyter -y
```
or
```
python3 -m venv /path/to/new/virtual/environment
```
and then activate it.

For additional useful guides see [1], [2], [3], [4]

## Using notebook template

You can automatically load this notebook template, with sections and headings preset for you. 

The key steps are:
1. In terminal, install jupytemplate by running:
```
pip install jupytemplate
```

2. Then, enable the extension in your local Jupyter instance:
```
jupyter nbextension install --py jupytemplate --sys-prefix
jupyter nbextension enable jupytemplate/main --sys-prefix
```

You will see a "Nbextensions" tab in Jupyter's tree view. In it, you can enable/disable the Template extension. If enabled, a new notebook will start from a preset template.


See [5] for more information.

In [12]:
# To install this custom EarthCube template, run the following to find the template location

import jupytemplate
print(jupytemplate.get_template_path())

C:\Users\izaslavsky\Anaconda3\envs\suave_prep\lib\site-packages\jupytemplate\jupytemplate\template.ipynb

Then replace the default template.ipynb with this notebook or with the short version (just headings and brief explanations).

Both the long and the short versions can be found at earthcube github.


To make the changes effective after replacing the template and renaming it to template.ipynb, run in terminal:
```
jupyter nbextension install --py jupytemplate --sys-prefix
jupyter nbextension enable jupytemplate/main --sys-prefix
```

## Adding table of contents

Having a table of contents below the title and authors will make your notebook look more professional, and will help users navigate it.

The key steps are:
1. In terminal, install jupyter_contrib_nbextensions
```
pip install --user jupyter_contrib_nbextensions
jupyter contrib nbextension install --user
```

2. Then, enable the Table of Contents extension:
```
jupyter nbextension enable toc2/main
```

You will see a new icon "Table of Contents" added to the row of icons. It will toggle the ToC view. Click the Gear icon on the ToC panel to add a ToC cell to your notebook.

See [5.1], [5.2] for more information

## Creating Docker and Binder for your notebook repository

Sharing just the Jupyter notebook .ipynb file is not sufficient for broad re-usability. We request that Jupyter notebooks are submitted to EarthCube in Binders. The Binder service is a free service that allows anyone to run notebooks from their web browser without installing any software and resolving dependencies. 

Follow these steps:
1. Assemble the Jupyter notebooks , environment files, custom external libraries, datasets, and a README, in a single project directory (and sub-directories off of it, as needed). Use GitHub to organize your project as a GitHub repository.

2. Optionally, test your project with repo2docker. See instructions in [2]. This will create a docker image which can be made available in a Docker repository. 

3. Create Binder. Use mybinder.org to create a URL for your notebook Binder (you will need to enter your GitHub repo URL). You can also add a Launch Binder button directly to your GitHub repo, by include the following in your README.md:
```
launch with myBinder
[![Binder](https://mybinder.org/badge.svg)](https://mybinder.org/v2/gh/<path to your repo>)
```

Specific projects may have their own Binder implementations. In this case, include a project-specific Binder reference so that reviewers can execure your code.

Expect the reviewers to use a browser of their choice to run your code, and avoid execution environments that have any special requirements that reviewers may not have (for example, Google colab requires a Google account, which reviewers may not have).

# References
List relevant references.

1. Notebook sharing guidelines from reproducible-science-curriculum: https://reproducible-science-curriculum.github.io/publication-RR-Jupyter/
2. Guide for developing shareable notebooks by Kevin Coakley, SDSC: https://github.com/kevincoakley/sharing-jupyter-notebooks/raw/master/Jupyter-Notebooks-Sharing-Recommendations.pdf
3. Guide for sharing notebooks by Andrea Zonca, SDSC: https://zonca.dev/2020/09/how-to-share-jupyter-notebooks.html
4. Jupyter Notebook Best Practices: https://towardsdatascience.com/jupyter-notebook-best-practices-f430a6ba8c69
5. Introduction to Jupyter templates nbextension: https://towardsdatascience.com/stop-copy-pasting-notebooks-embrace-jupyter-templates-6bd7b6c00b94  
    5.1. Table of Contents (Toc2) readthedocs: https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/toc2/README.html  
    5.2. Steps to install toc2: https://stackoverflow.com/questions/23435723/installing-ipython-notebook-table-of-contents
6. Rule A, Birmingham A, Zuniga C, Altintas I, Huang SC, et al. (2019) Ten simple rules for writing and sharing computational analyses in Jupyter Notebooks. PLOS Computational Biology 15(7): e1007007. https://doi.org/10.1371/journal.pcbi.1007007. Supplementary materials: example notebooks (https://github.com/jupyter-guide/ten-rules-jupyter) and tutorial (https://github.com/ISMB-ECCB-2019-Tutorial-AM4/reproducible-computational-workflows)
7. Languages supported by Jupyter kernels: https://github.com/jupyter/jupyter/wiki/Jupyter-kernels
8. EarthCube notebooks presented at EC Annual Meeting 2020: https://www.earthcube.org/notebooks